name: BLiveChat PyInstaller

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: 'frontend'
      - name: Yarn build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: 'frontend'
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install Packages
        run: pip install -r requirements.txt
      - name: PyInstaller
        run: pyinstaller blivechat.spec
      - uses: actions/upload-artifact@v3
        with:
          name: blivechat-win64
          path: dist/blivechat
